config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'gurus',
                     path_name: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  root 'tests#index'

  delete :logout, to: 'sessions#destroy'

  get '/badges', to: 'badges#index'
  get '/user_badges', to: 'badges#user_badges'

  resources :tests, only: :index do
    post :start, on: :member
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end

  get '/tests/:category/:title', to: 'tests#search'

  get '/contact', to: 'contacts#new'
  post '/contact', to: 'contacts#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
    # save current URL to use it in link Back in Questions#show
    cookies[:original_url] = request.url
  end
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to gist.question.body[0..25], admin_question_path(gist.question) %></td>
  <td><%= link_to gist.github_id, gist.url, target: :blank %></td>

  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<h1><%= t('.header') %></h1>

<table border="1" cellpadding="7" cellspacing="0">
  <tr>
    <th><%= t('.question') %></th>
    <th><%= t('.link_to_github') %></th>
    <th><%= t('.email') %></th>
  </tr>

  <%= render @gists %>
</table>