config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'gurus',
                     path_name: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  root 'tests#index'

  delete :logout, to: 'sessions#destroy'

  get '/badges', to: 'badges#index'
  get '/user_badges', to: 'badges#user_badges'

  resources :tests, only: :index do
    post :start, on: :member
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end

  get '/tests/:category/:title', to: 'tests#search'

  get '/contact', to: 'contacts#new'
  post '/contact', to: 'contacts#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :nullify
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSAGE_PERCENTAGE_OF_CORRECT_ANSWERS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def success?
    return false if test.timer && time_is_out?
    percent_of_corrent_answers >= PASSAGE_PERCENTAGE_OF_CORRECT_ANSWERS
  end

  def percent_of_corrent_answers
    (correct_questions.to_f / test.questions.count * 100).to_i
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def time_is_out?
    passage_time >= test.timer
  end

  def passage_time
    (Time.now.utc - created_at.utc).to_i
  end

  private

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    #correct_answers.ids.sort == answer_ids.map(&:to_i).sort

    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result
    TestsMailer.completed_test(@test_passage).deliver_now
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      if @test_passage.success?
        service = BadgesAwardService.new(@test_passage)
        service.call
        if service.awarded?
          flash.notice = "You were given a new badge.
                          #{ActionController::Base.helpers.link_to 'Watch now', user_badges_path}"
        end
      end

      redirect_to result_test_passage_path(@test_passage)
      return
    end

    render :show
  end

  def gist
    current_question = @test_passage.current_question
    service = GistQuestionService.new(current_question)
    response_body = service.call
    if service.success?
      create_gist_in_bd(response_body, current_question, current_user)

      flash_options =
        { notice: t(
          '.success',
          gist_url: ActionController::Base.helpers.link_to(
            t('.gist_link'),
            response_body['html_url'],
            target: :blank
          )
        ) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def create_gist_in_bd(response_body, question, user)
    Gist.create(
      url: response_body['html_url'],
      question: question,
      user: user,
      github_id: response_body['id']
    )
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def show_result
    if @test_passage.success?
      ("<h2 style='color:green'>#{result_message}<br>Congratulations! You have passed the test.</h2>").html_safe
    else
      ("<h2 style='color:red'>#{result_message}<br>You haven't passed the test.</h2>").html_safe
    end
  end

  def result_message
    "Your result is #{@test_passage.percent_of_corrent_answers} %.
    Passage time: #{human_passage_time(@test_passage)}."
  end

  def human_passage_time(test_passage)
    ActiveSupport::Duration.build(test_passage.passage_time).inspect
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<div class="progress-bar-container">
  <div class="progress-bar" style="font-size:11px; text-align:left; color:#09083B">
    Test passage progress
  </div>
</div>

<script type="text/javascript">
  document.querySelector('.progress-bar').style.width = "100%"
</script>

<%= show_result %>

<%= link_to 'Back to all tests', tests_path %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<% if @test_passage.test.timer %>
  You should pass the test in <%= human_passage_time(@test_passage) %><br>
  Current passage time:
  <%= content_tag :div, '',
                        class: "timer",
                        data: { result_url: "/test_passages/#{@test_passage.id}/result",
                        timer: @test_passage.test.timer,
                        start_time: (@test_passage.created_at.to_f * 1000).to_i} %>
<% end %>

<div class="progress-bar-container">
  <div class="progress-bar" style="font-size:11px; text-align:left; color:#09083B">
    Test passage progress
  </div>
</div>

<script type="text/javascript">
  <% if @test_passage.current_question == @test_passage.test.questions[0] %>
    var percent = 0
  <% else %>
  var percent = <%= (@test_passage.test.questions.index(@test_passage.current_question).to_f / @test_passage.test.questions.count * 100).to_i %>
  <% end %>
  document.querySelector('.progress-bar').style.width = (percent + "%")
</script>

Question No. <%= @test_passage.test.questions.index(@test_passage.current_question) + 1 %>
  out of <%= @test_passage.test.questions.size %>: <br>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next' %></p>
<% end %>