config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'gurus',
                     path_name: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  root 'tests#index'

  delete :logout, to: 'sessions#destroy'

  get '/badges', to: 'badges#index'
  get '/user_badges', to: 'badges#user_badges'

  resources :tests, only: :index do
    post :start, on: :member
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end

  get '/tests/:category/:title', to: 'tests#search'

  get '/contact', to: 'contacts#new'
  post '/contact', to: 'contacts#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'js-resource-errors', data: { resource_id: resource.id } do %>
<!--     <h2><%#= pluralize(resource.errors.count, 'error') %> detected:</h2>
 -->
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
<div class="<%= flash_class(key) %>" role="alert">
  <%= message.html_safe %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  <!-- content_tag :p, message, class: "flash #{key}" -->
<% end %>

app/views/shared/_get_started_nav.html.erb
<div class="navbar" id="navbarNavDropdown">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <%= link_to t('login'), new_session_path(resource_name), class: 'nav-link' %>
    </li>

    <li class="nav-item active">
      <%= link_to t('signup'), new_registration_path(resource_name), class: 'nav-link' %>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= t('language') %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "English", { :lang=>'en' }, class: 'dropdown-item' %>
        <%= link_to "Русский", { :lang=>'ru' }, class: 'dropdown-item' %>
      </div>
    </li>
  </ul>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if user_signed_in? %>
    <%= render 'shared/signed_in_user_nav' %>
  <% else %>
    <%= render 'shared/get_started_nav' %>
  <% end %>
</nav>

app/views/shared/_signed_in_user_nav.html.erb
<ul class="navbar-nav">
  <div class="btn-group" role="group" aria-label="Basic example">
  <!--   In case admin enters root_path: -->
    <% if current_user.admin? %>
      <button type="button" class="btn btn-primary custom">
        <%= link_to t('admin_panel'), admin_root_path, class: 'navbar-brand' %>
      </button>
    <% end %>
  <!--   --------------    -->
    <button type="button" class="btn btn-success custom">
      <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    </button>
  </div>
</ul>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse d-sm-md-flex flex-row-reverse" id="navbarNavDropdown">
  <ul class="navbar-nav">
    <li class="nav-item">
      <span class="navbar-text">
        <%= t('welcome_html', name: current_user.first_name) %>
      </span>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= t('language') %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "English", { :lang=>'en' }, class: 'dropdown-item' %>
        <%= link_to "Русский", { :lang=>'ru' }, class: 'dropdown-item' %>
      </div>
    </li>

    <li class="nav-item active">
      <%= link_to t('contact_form'), contact_path, class: 'nav-link' %>
    </li>

    <li class="nav-item active">
      <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  </ul>
</div>